version: "3.8"

services:
  backend:
    build:
      context: ./backend
    # ports:
    #   - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge
